### PR TITLE
Remove Cython import at setup.py

### PR DESCRIPTION
**Pull request by kuenishi**
setuptools newer than 18.0 now automatically detect Cython and does
not require explicit Cython installation before. See also:

- http://setuptools.readthedocs.io/en/latest/history.html#id273
- https://github.com/pypa/setuptools/issues/288

### CODE REVIEW

**Comment by iwiwi** [comment]
Could you also remove manual installation of Cython at Travis CI?

https://github.com/chainer/chainermn/blob/master/.travis.yml#L46

**Comment by kuenishi** [comment]
I removed cython installation at travis setup. Meanwhile I doubt we really need both mpi4py and cffi. For now I'll leave it as it is.

**Comment by iwiwi** [comment]
Did you test locally? I tested it locally, and I found that `chainermn/nccl/nccl.c` is not produced, and thus it fails. 😢 

```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing chainermn.egg-info/PKG-INFO
writing dependency_links to chainermn.egg-info/dependency_links.txt
writing requirements to chainermn.egg-info/requires.txt
writing top-level names to chainermn.egg-info/top_level.txt
reading manifest file 'chainermn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxi' under directory 'chainermn'
writing manifest file 'chainermn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'chainermn.nccl.nccl' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/akiba/.pyenv/versions/tmp1/include/python3.6m -c chainermn/nccl/nccl.c -o build/temp.linux-x86_64-3.6/chainermn/nccl/nccl.o
gcc: error: chainermn/nccl/nccl.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 1
```

FYI: Our Cython module is not built on Travis, as it depends on NCCL, which depends on CUDA. Previously we installed Cython only to satisfy `import` in `setup.py`.

**Comment by kuenishi** [comment]
I tested it with `pip install .` and it worked. I'll try and see what happens.

**Comment by iwiwi** [comment]
Please be sure that Cython is not installed in your env

**Comment by gwtnb** [comment]
Cython installation is required to generate C source files from Cython source files.

**Comment by kuenishi** [comment]
I uninstalled Cython for sure but previously generated `nccl.c` remained at my tests.

**Comment by kuenishi** [comment]
... but anyway pip worked and setup.py didn't. I'll consider using a hack like cupy's.

**Comment by iwiwi** [comment]
I remember that our plan is to remove our NCCL binding from ChainerMN and will rely on cupy's NCCL binding in near future. So, if it is not very easy, I don't think we need to work on this on our own.

**Pull request closed without merging**
