### PR TITLE
Fix the way to import cudnn

### PR DESCRIPTION
**Pull request by mitmul**
CuPy v4.0.0b1 introduces the cythonized cuDNN interfaces. It seems to modify the module name of cupy.cudnn. This PR avoids the importing error due to that modification.

### CODE REVIEW

**Comment by mitmul** [comment]
I got an advise from Okuta-sensei about how to import cudnn in the right way. I updated this PR.

**Comment by tkerola** [comment]
Oh sorry, I also sent a PR (#147) about this issue. My solution was just to remove those lines, since they are not used in the code. I wonder if you have a specific reason to keep them in the code?

**Comment by kuenishi** [comment]
Just curious that [Chainer 4.0.0b1 has the exactly same code](https://github.com/chainer/chainer/blob/v4.0.0b1/chainer/functions/normalization/batch_normalization.py#L10-L12) and why it is (supposed to be) working correctly?

From me it looks good to remove the if clause as no cudnn and libcudnn seem to be needed in this file (in contrast to Chainer's heavy usage of cudnn).

**Comment by tkerola** [comment]
Chainer has not the same code: `libcudnn = cuda.cuda.cudnn` ChainerMN has: `libcudnn = cudnn.cudnn`. The latter doesn't work with CuPy v4.
I agree with removing the code. Probably flake8 doesn't check unused non-top-level imports.

**Comment by mitmul** [comment]
Thanks @tkerola , I think that's better choice so I close this PR.

**Comment by kuenishi** [comment]
ummm, many `cu` s, confusing. I'll be testing #147 and will merge eventually.

**Pull request closed without merging**
