### PR TITLE
Replace get_device 

### PR DESCRIPTION
**Pull request by shu65**
This PR replaces get_device because it is deprecated in new version of Chainer.

### CODE REVIEW

**Comment by kuenishi** [comment]
Is this still WIP? Changes seems good to me.

**Comment by shu65** [comment]
I have not confirmed the execution of all examples yet. I will change it after confirming them.

**Comment by kuenishi** [comment]
c.f. https://docs.chainer.org/en/v4.0.0/reference/util/generated/chainer.backends.cuda.get_device.html#chainer.backends.cuda.get_device

**Comment by kuenishi** [comment]
Examples have been all tested.

**Pull request merged**
